### ISSUE TITLE
get_trends gives me this error and I dont know why 

### ISSUE THREAD

**Issue by zachadams16** [bisguzar/twitter-scraper#108]
/Users/zachadams/Desktop/scraper/venv/bin/Python /Users/zachadams/Desktop/scraper/scape.py
Traceback (most recent call last):
  File "/Users/zachadams/Desktop/scraper/scape.py", line 10, in <module>
    trends = get_trends()
  File "/Users/zachadams/Desktop/scraper/venv/lib/python3.7/site-packages/twitter_scraper-0.4.0-py3.7.egg/twitter_scraper/modules/trends.py", line 9, in get_trends
  File "/Users/zachadams/Desktop/scraper/venv/lib/python3.7/site-packages/requests-2.23.0-py3.7.egg/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bisguzar** [comment]
Hi @zachadams16  thanks for your report. Can you check and test #109 , it will solve this problem. Please leave a comment to pull request so I can merge it with quietude.

**Comment by tuchang** [comment]
I have the same issue. #109 seems to be " No description provided. "
