### ISSUE TITLE
Can't import library

### ISSUE THREAD

**Issue by sldx12** [bisguzar/twitter-scraper#121]
This works perfectly on my computer, however, I'm trying to work with this in a server (which I do not have sudo permissions) and I can't import it. I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "twitter_scraper/__init__.py", line 1, in <module>
    from .modules.profile import Profile
  File "twitter_scraper/modules/profile.py", line 27
    "Referer": f"https://twitter.com/{username}",
                                               ^
SyntaxError: invalid syntax
```

Since, as I said, I don't have sudo permissions, I have to install it from pip.

**Comment by sldx12** [comment]
Fixed it. Was using Python .
