### ISSUE TITLE
UnboundLocalError: local variable 'html' referenced before assignment

### ISSUE THREAD

**Issue by jalilrooney** [bisguzar/twitter-scraper#166]
I tried a basic profile selection:

`profile = Profile(user_name)`

And the I got this error:
```
File "/usr/local/lib/python3.6/site-packages/twitter_scraper/modules/profile.py", line 65, in __parse_profile
    self.location = html.find(".ProfileHeaderCard-locationText")[0].text
UnboundLocalError: local variable 'html' referenced before assignment
```

I believe that something changed on twitter website

**Comment by pradeepbatchu** [comment]
I also got same issue, below is the error 
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): twitter.com:443
DEBUG:urllib3.connectionpool:https://twitter.com:443 "GET /pradeepbatchu HTTP/1.1" 400 None
Traceback (most recent call last):
  File "D:/twitt.py", line 15, in <module>
    gettwitter_profile('pradeepbatchu')
  File "D:/twitt.py", line 7, in gettwitter_profile
    profile = Profile(twitter_handler)
  File "C:\Users\prade\anaconda3\lib\site-packages\twitter_scraper\modules\profile.py", line 41, in __init__
    self.__parse_profile(page)
  File "C:\Users\prade\anaconda3\lib\site-packages\twitter_scraper\modules\profile.py", line 65, in __parse_profile
    self.location = html.find(".ProfileHeaderCard-locationText")[0].text
UnboundLocalError: local variable 'html' referenced before assignment
```

**Comment by LeiLuo2020** [comment]
I also got the same error to what jalilrooney reported.

**Comment by yimingStar** [comment]
It seems like the old version server side render api has been closed.
Some selector columns need to change, since the new webpage did not contain the same column.

**Comment by danielp3011** [comment]
I have the same error. Can somebody point out a way to solve it. Sadly I'm not an experienced cooder yet. How did you solve this with the User-Agent @yimingStar? Can you explain that in detail?
That would be nice! Thanks a lot

**Comment by yimingStar** [comment]
Hi, @danielp3011 
I made a pull request here - https://github.com/bisguzar/twitter-scraper/pull/167

Since the original page cannot show up, I use another user-agent to get a mobile version web page (mobile.twitter.com).
Next, we'll try to rewrite the selector because the page element is different.
By the way, there still are some elements I cannot get, but most of them are fine.

**Comment by bisguzar** [comment]
Please leave a review for PR @danielp3011 . So I can merge it easyly. Thanks for your efforts guys!

**Comment by Altimis** [comment]
Twitter scrapers API dont seem to work anymore due to Twitter API changes. This [solution](https://github.com/Altimis/Scweet) doesnt need authentification, doesnt depend on Twitter API and sufficiently efficient.

**Comment by J0ANMM** [comment]
Should this fix still be working? 
I tried it on my local file but I am still getting the 'html' error...

**Comment by rinaldipratama** [comment]
Same, I still got the error. "UnboundLocalError: local variable 'html' referenced before assignment."

**Comment by Bitcoinera** [comment]
getting the same error here. Is there no workaround?

**Comment by mominurr** [comment]
I am getting same error.
