### ISSUE TITLE
UnboundLocalError: local variable 'html' referenced before assignment

### ISSUE THREAD

**Issue by sscanavini** [bisguzar/twitter-scraper#173]
When I try to:

profile = Profile('bgpstream')

I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tools/tmp/twitter-scraper/twitter_scraper/modules/profile.py", line 41, in __init__
    self.__parse_profile(page)
  File "/tools/tmp/twitter-scraper/twitter_scraper/modules/profile.py", line 65, in __parse_profile
    self.location = html.find(".ProfileHeaderCard-locationText")[0].text
UnboundLocalError: local variable 'html' referenced before assignment

**Comment by yimingStar** [comment]
@sscanavini  please check #166 
It is the same issue, due to an empty response.

**Comment by r4cs** [comment]
same here

**Comment by Altimis** [comment]
@r4cs 
@yimingStar 
Please check my work [scweet](https://github.com/Altimis/Scweet). No auhenitification is needed and it is very efficient.

**Comment by Modem-i4** [comment]
Same

**Comment by TrevorBagels** [comment]
I'm also getting this, anyone know any workarounds?
