### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by CarloCobal** [bisguzar/twitter-scraper#191]
If so how?

**Comment by bisguzar** [comment]
Not working for now, refactor/fix required.

**Comment by nsde** [comment]
```
Traceback (most recent call last):
  File "/home/lix/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/lix/.local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/lix/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/lix/.local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lix/anaconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 170, in get_tweets
    yield from gen_tweets(pages)
  File "/home/lix/anaconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 37, in gen_tweets
    html=r.json()["items_html"], url="bunk", default_encoding="utf-8"
  File "/home/lix/.local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
```

**Comment by bisguzar** [comment]
Still not working @nsde . I'm not sure will I fix it. PRs are welcome.

**Comment by psylopunk** [comment]
Still not working :(

**Comment by mahrtayyab** [comment]
You can try this https://github.com/mahrtayyab/tweety

**Comment by FarisHijazi** [comment]
do you know where the issue is? to get us started and save us time

**Comment by shelsoloa** [comment]
@FarisHijazi I'm going to look into this a bit today. Any chance you found the start of the issue? The error linked by @nsde is the same one I'm experiencing.

**Comment by mahrtayyab** [comment]
Give it a try https://github.com/mahrtayyab/tweety

**Comment by shelsoloa** [comment]
@mahrtayyab works for me - thanks!

**Comment by ege-del** [comment]
@bisguzar can the repo owner please weigh in ? Since I am not familiar with Twitter's API (they wont let me use it), I cant figure out why it's not working. Which one of these is more likely ?

1. They blocked the method this project uses
2. Updated API causes faulty requests
3. Other bugs in the project itself

**Comment by bisguzar** [comment]
I guess the first one, but I didn't debug it yet. I'm just predicting @ege-del

**Comment by david1asher** [comment]
not working for me
