### ISSUE TITLE
json.decoder.JSONDecodeError: in get_tweets()

### ISSUE THREAD

**Issue by jmoraes7** [bisguzar/twitter-scraper#201]
I'm trying to run the following code example from the documentation: 

`Python 3.7.3 (default, Mar 26 2019, 21:43:19) 
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from twitter_scraper import get_tweets
>>> 
>>> for tweet in get_tweets('jdzie_', pages=1):
...     print(tweet['text'])`

but end up hitting this error:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/miniconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 170, in get_tweets
    yield from gen_tweets(pages)
  File "/Users/username/miniconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 37, in gen_tweets
    html=r.json()["items_html"], url="bunk", default_encoding="utf-8"
  File "/Users/username/miniconda3/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Anyone know why this is happening? Is this project still being maintained?

**Comment by sourface94** [comment]
Were you able to solve this?

**Comment by sourface94** [comment]
> I'm trying to run the following code example from the documentation:
> 
> `Python 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > from twitter_scraper import get_tweets
> > > > for tweet in get_tweets('jdzie_', pages=1):
> > > > ...     print(tweet['text'])`
> 
> but end up hitting this error:
> 
> `Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/Users/username/miniconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 170, in get_tweets yield from gen_tweets(pages) File "/Users/username/miniconda3/lib/python3.9/site-packages/twitter_scraper/modules/tweets.py", line 37, in gen_tweets html=r.json()["items_html"], url="bunk", default_encoding="utf-8" File "/Users/username/miniconda3/lib/python3.9/site-packages/requests/models.py", line 975, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
> 
> Anyone know why this is happening? Is this project still being maintained?

Were you able to solve this?

**Comment by jmoraes7** [comment]
hey unfortunately not - ended up building our own scraper instead. still hoping someone figures out a solution though

what about you?

**Comment by sourface94** [comment]
> hey unfortunately not - ended up building our own scraper instead. still hoping someone figures out a solution though
> 
> what about you?

No I havent, are you able to share your scraper?

**Comment by sweetbbak** [comment]
I have this issue still as well.

**Comment by devAyushDubey** [comment]
Did anyone find a work around?

**Comment by Mcrich23** [comment]
@jmoraes7 link?

**Comment by CatBraaain** [comment]
same here
