### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by specu** [bisguzar/twitter-scraper#70]
script:
```
from twitter_scraper import get_tweets
for twitter_acct in [ "xbox", "Minecraft", "VuduFans", "minecraftearth" ]:
    for tweet in get_tweets(twitter_acct, pages=1):
        print(tweet['text'])

```
causes exception:
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    for tweet in get_tweets(twitter_acct, pages=1):
  File "/usr/local/lib/python3.6/site-packages/twitter_scraper.py", line 78, in get_tweets
    yield from gen_tweets(pages)
  File "/usr/local/lib/python3.6/site-packages/twitter_scraper.py", line 35, in gen_tweets
    text = tweet.find('.tweet-text')[0].full_text
IndexError: list index out of range
```
Hopefully you can reproduce it on your side

**Comment by bisguzar** [comment]
Hi, I think you installed project from PyPI (with pip). The PyPI version is outdated :( I will publish current version ASAP, waitin' reply from @kennethreitz . Your problem looks like fixed #50 #52
